# Wczytywanie słynnych konfiguracji Marcina w Python

Na podstawie programu decode.py (https://github.com/D3M80L/CA/blob/master/phd/decode.py) napisałem poniższe funkcje, które można użyć w ramach notebooka. Należy pamiętać, aby plik z konfiguracjami pobrany https://github.com/D3M80L/CA/tree/master/phd/data umieścić w tym samym folderze co nasz notebook Pythonowy.

Uwaga! 
1. Moja implementacja wczytuje wszystkie konfiguracje do pamięci operacyjnej. Dla małych zbiorów danych to jest najlepsze wyjście - będzie najszybciej, ale gdybyśmy obrabiali zbiory, które ważą setki albo tysiące MB, trzebaby wymyślić inne wyjście.
2. Moja implementacja nie jest optymalne i pewnie dla większych zbiorów da się to napisać lepiej. Nie mniej dla rozsądnych długości do kilkuset MB, powinno działać dobrze.

In [23]:
import numpy as np
import math

def convert_configuration(configuration: bytes, N: int):
    binary_str = ''.join(f'{byte:08b}' for byte in configuration)
    return np.array([int(bit) for bit in binary_str[:N]])

def configuration_reader(file_name: str, N: int, negate: bool):
    bytes_per_configuration = math.ceil(N / 8)
    configurations = []

    with open(file_name, 'rb') as file:
        while True:
            bytes_read = file.read(bytes_per_configuration)
            if not bytes_read:
                break

            cfg = convert_configuration(bytes_read, N)
            configurations.append(cfg)
            
            if negate:
                configurations.append(1 - cfg)

    return np.stack(configurations)

Poniżej przykład użycia napisanej przeze mnie funkcji. Zwróć uwagę, że musimy jako drugi argument funkcji podać długość konfiguracji zapisanych w pliku. Format plików, które stowrzył Marcin jest taki, że plik sam z siebie "nie wie" jakiej długości konfiguracje są w nim zapisane - czyli tej długości nie da się odczytać ze środka pliku. 

Trzeci paramter mówi o tym czy w wynikowej liście mają znaleźć się też "zanegowane" konfiguracje. Jeśli podamy False, to wszystkie otrzymane konfiguracje będą miały gęstość mniejszą niż 0.5. A jeśli podamy True, to dostaniemy zarówno takie, których gęstość jest mniejsza jaki i większa od 0.5.

In [24]:
configurations = configuration_reader("ALL_N21.bin", 21, True)
configurations2 = configuration_reader("ALL_N21.bin", 21, False)

Poniże wyświetlam kilka pierwszych wczytanych konfiguracji, żeby sprawdzić czy to działa. 

In [25]:
print(configurations[0:10])
print(configurations2[0:10])

[[0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 1 0 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 0 0 0 0 1 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 1 1 1 0 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 1 1]
 [0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0 1]]
